### ISSUE TITLE
Libs used to record the results

### ISSUE THREAD

**Issue by mp-17** [embench/embench-iot-results#1]
Hello everyone,

It is not clear to me which libraries were used during the building of the benchmarks.
I was trying to reproduce the size results of ri5cy-gcc-9.2-version-os-save-restore. 
In the corresponding file in the folder **results** I see: 

>   "tool chain information" :
>   { "tool chain version" :
>     { "compiler" : "gcc commmit/tag gcc-9_2_0-release",
>       "linker" : "ld commit/tag binutils-2_32",
>       "C library" : "newlib commit/tag newlib-3.1.0"
>     },

Were the benchmarks linked with dummy libraries as suggested by the Embench documentation?
Because I read (in the part cited above) the information about the C library of the toolchain, and in the LD Flags I do not see any option like "-nostdlib" that can help link the dummy libraries.

Thank you very much,
Matteo

**Comment by jeremybennett** [comment]
Hi Matteo,

Hopefully the new repository structure addresses this. You can click on any result and it will tell you what library was used and how it was configured.

HTH,


Jeremy
