### ISSUE TITLE
Specify reference platform and its absolute data

### ISSUE THREAD

**Issue by mp-17** [embench/embench-iot-results#2]
Hello everyone,

I think these data belong to the past because the reference platform was changed from RISC-V to ARM Cortex-M4.
Maybe it could be better to specify in the readme which is the reference platform related to these results, together with the reference platform absolute data both for speed and code size.

Kind regards,
Matteo Perotti

**Comment by jeremybennett** [comment]
Hi Matteo,

They do. I am working to have the new version ready before our monthly call on Monday.

Watch this space...

Best wishes,


Jeremy

**Comment by jeremybennett** [comment]
Hi Matteo,

Finally got the correct data. Feeback on these very welcome.

Thanks,


Jeremy
